/**
 * Benchmark: lume-ssr vs other JSX-to-HTML renderers.
 *
 * Workload: a realistic page - header, nav, a 100-row / 5-column table with
 * text that needs escaping, and a footer. Built with each library's
 * createElement-style API (no build step) and rendered to a string.
 *
 *   cd bench && npm install && npm run bench
 */
import { performance } from 'node:perf_hooks';

const ROWS = Array.from({ length: 100 }, (_, i) => ({
    id: i,
    name: `User <${i}> "quoted"`,
    email: `user${i}@example.com`,
    role: i % 3 === 0 ? 'admin' : 'member',
    active: i % 2 === 0
}));

const NAV = ['Home', 'Products', 'Pricing', 'Docs', 'About'];

// Build the same page shape for any createElement(tag, props, ...children)
function page(el) {
    return el('html', { lang: 'en' },
        el('head', null, el('title', null, 'Benchmark')),
        el('body', null,
            el('header', { class: 'site-header' },
                el('h1', null, 'Dashboard'),
                el('nav', null, NAV.map(n =>
                    el('a', { href: `/${n.toLowerCase()}`, class: 'nav-link' }, n)
                ))
            ),
            el('main', null,
                el('table', { class: 'data' },
                    el('thead', null, el('tr', null,
                        ['ID', 'Name', 'Email', 'Role', 'Active'].map(t => el('th', null, t))
                    )),
                    el('tbody', null, ROWS.map(r =>
                        el('tr', { class: r.active ? 'active' : 'inactive' },
                            el('td', null, String(r.id)),
                            el('td', null, r.name),
                            el('td', null, el('a', { href: `mailto:${r.email}` }, r.email)),
                            el('td', null, r.role),
                            el('td', null, r.active ? 'yes' : 'no')
                        )
                    ))
                )
            ),
            el('footer', null, el('p', null, 'Generated by benchmark & escaped <safely>'))
        )
    );
}

function bench(name, fn, { warmup = 200, iterations = 1000 } = {}) {
    for (let i = 0; i < warmup; i++) fn();
    const start = performance.now();
    for (let i = 0; i < iterations; i++) fn();
    const ms = performance.now() - start;
    const opsPerSec = Math.round((iterations / ms) * 1000);
    return { name, opsPerSec, msPerOp: (ms / iterations).toFixed(3) };
}

const results = [];

// lume-ssr
{
    const { h, renderToString } = await import('../src/index.js');
    const out = renderToString(page(h));
    results.push({ ...bench('lume-ssr', () => renderToString(page(h))), bytes: out.length });
}

// react-dom/server
try {
    const React = (await import('react')).default;
    const { renderToString } = await import('react-dom/server');
    const el = (tag, props, ...children) => React.createElement(tag, props, ...children);
    const out = renderToString(page(el));
    results.push({ ...bench('react-dom/server', () => renderToString(page(el))), bytes: out.length });
} catch (e) { console.error('skip react:', e.message); }

// preact-render-to-string
try {
    const { h } = await import('preact');
    const { renderToString } = await import('preact-render-to-string');
    const out = renderToString(page(h));
    results.push({ ...bench('preact-render-to-string', () => renderToString(page(h))), bytes: out.length });
} catch (e) { console.error('skip preact:', e.message); }

// @kitajs/html
try {
    const { createElement } = await import('@kitajs/html');
    const el = (tag, props, ...children) => createElement(tag, props, ...children);
    const out = page(el);
    results.push({ ...bench('@kitajs/html', () => page(el)), bytes: String(out).length });
} catch (e) { console.error('skip kitajs:', e.message); }

// hono/jsx
try {
    const { jsx } = await import('hono/jsx');
    const el = (tag, props, ...children) => jsx(tag, props ?? {}, ...children);
    const out = el && page(el).toString();
    results.push({ ...bench('hono/jsx', () => page(el).toString()), bytes: out.length });
} catch (e) { console.error('skip hono:', e.message); }

results.sort((a, b) => b.opsPerSec - a.opsPerSec);
const pad = (s, n) => String(s).padEnd(n);
console.log(`\nNode ${process.version} | 100-row table page (~${Math.round(results[0].bytes / 1024)}KB HTML)\n`);
console.log(pad('renderer', 26) + pad('ops/sec', 12) + pad('ms/op', 10) + 'output bytes');
for (const r of results) {
    console.log(pad(r.name, 26) + pad(r.opsPerSec, 12) + pad(r.msPerOp, 10) + r.bytes);
}
